### ISSUE TITLE
Not working on iPad air 2

### ISSUE THREAD

**Issue by IAMtheIAM** [equinusocio/help-media-queries#3]
It works on desktop, but on iPad Air 2 Safari, nothing appears. I did remote debugging and the `:after` psudo-element doesnt appear in the html. Does it not work on iPad? Works great on desktop though :-D

**Comment by equinusocio** [comment]
The tooltip should appear always starting from the smaller breakpoint:

```
$breakpoints: (
  extraSmall : 30em,
  small      : 48em,
  medium     : 60em,
  large      : 80em,
  extraLarge : 100em
);
```

**Comment by IAMtheIAM** [comment]
It does not work on iPad unfortunately. Here is a minimal reproduction.

https://embed.plnkr.co/jeWy7J6Nzy7YMf6WtpES/
or use this http://bit.ly/2zjoWfn (easier to type on iPad)

On desktop, works fine. Opening that on an iPad results in no tooltip.

**Comment by IAMtheIAM** [comment]
I found the solution. Its this that prevents it from working

```scss
               &::after {
          @media screen and ( $dpi ) {
            content: 'Density: #{ $density-value }';
```

the `and ( $dpi ) ` doesn't trigger on iPad. Removing it so it just says 
```scss

        &::after {
          @media screen and ( $dpi ) {
            content: 'Density: #{ $density-value }';
// rest here
```

then it works. I'm not sure what the purpose of the $dpi is because it works without it.
